fixed bug: update git workflow

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -25,7 +25,14 @@ jobs:
 
       - name: Get version from tag
         id: get_version
-        run: echo "VERSION=${GITHUB_REF#refs/tags/}"
+        run: |
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            VERSION=${GITHUB_REF#refs/tags/}
+            echo "VERSION=${VERSION}" >> $GITHUB_ENV
+          else
+            echo "Error: No valid tag found!" >&2
+            exit 1
+          fi
 
       - name: Build Application Image
         run: |
